### ISSUE TITLE
Update approach to how we manage and configure the weave network

### ISSUE THREAD

**Issue by tayzlor** [Capgemini/Apollo#395]
See http://blog.weave.works/2015/07/16/bridge-over-troubled-weavers/

As part of this we also need to update the docs here https://github.com/Capgemini/Apollo/tree/master/roles/weave

and the blog post here http://capgemini.github.io/devops/how-apollo-uses-weave

**Comment by enxebre** [comment]
Dropped a comment here
https://github.com/weaveworks/weave/issues/117#issuecomment-124075671

**Comment by enxebre** [comment]
this needs to be fix as part of this ticket https://github.com/Capgemini/Apollo/issues/325

**Comment by pmbauer** [comment]
At udacity, we've observed an extremely high price for using the weave overlay network for container-to-container communication. (aws, vpc).
Using qperf, we've measured the following relative bandwidths (1x is over VPC)
eth0-hostA -> eth0-hostB : 1x
eth0-hostA -> weave-hostB: .5x
weave-hostA -> weave-hostB: .05x

Dial-up modem speeds over the weave overlay network is unusable.

So we will be spending time in our following sprint to sort this out.  Just checking if anyone else had observed this and had tried out weave-managed device and weave-allocated IP blocks (per the troubled-weavers post); didn't want to duplicate work.

**Comment by enxebre** [comment]
Hi, we've been waiting for https://github.com/weaveworks/weave/pull/1376 to get merged as otherwise the new weave approach (not overriding docker dockerbridge) will break the consul/registrator/weave discovery ecosystem (see https://github.com/weaveworks/weave/issues/117#issuecomment-124075671)
The "fix" is included in new version of weave so this new approach could be tested now.
 
We also want to move to fast datapath http://blog.weave.works/2015/06/12/weave-fast-datapath/ which is unstable and linked to an old version of weave at the moment but hopefully will have some improvements in the next release of weave.
To answer your question there is no work in progress for this at the minute.

**Comment by pmbauer** [comment]
@enxebre Thanks for the summary; I'll report back when we try the new version of weave, probably late next week.

**Comment by enxebre** [comment]
Hey @pmbauer we've just made a priority if this as well as move to fastdatapath which is just been released https://github.com/weaveworks/weave/releases/tag/v1.2.0
So we are starting to work on this, any feedback from your side would be appreciate :)

**Comment by pmbauer** [comment]
@enxebre nice! things happen at work as they do. A bunch of other tasks trumped our weave re-work so I don't have anything to report yet unfortunately.

**Comment by enxebre** [comment]
closing as this got it https://github.com/Capgemini/Apollo/pull/504
